name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    container:
      image: php:8.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Variables
        run: |
          echo "DEPLOY_USER=${{ vars.DEPLOY_USER }}"
          echo "DEPLOY_HOST=${{ vars.DEPLOY_HOST }}"
          echo "DEPLOY_DIR=${{ vars.DEPLOY_DIR }}"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%b\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
#          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > ~/.ssh/config
#          chmod 644 ~/.ssh/config

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y libzip-dev libpng-dev zip wget rsync openssh-client
          docker-php-ext-install zip gd bcmath pdo_mysql
          wget -O /usr/local/bin/composer https://getcomposer.org/download/latest-stable/composer.phar
          chmod +x /usr/local/bin/composer
          composer install && composer dump-autoload

      - name: Set up environment
        run: |
          echo "${{ vars.DEPLOY_ENV_FILE }}" > .env
          echo "OK" > public/health.html

      - name: Deploy using rsync and migrate
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ vars.DEPLOY_USER }}@${{ vars.DEPLOY_HOST }} \
            "source ~/.profile && cd ${{ vars.DEPLOY_DIR}} && php artisan migrate "
