name: PHP CS and Hash Key Check

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  check-php-cs:
    name: Check PHP Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHP CodeSniffer
        run: |
          composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP CodeSniffer
        run: |
          OUTPUT=$(~/.composer/vendor/bin/phpcs --standard=PSR2 app/ || true)
          if [ ! -z "$OUTPUT" ]; then
            echo "PHP CS lỗi:"
            echo "$OUTPUT"
            COMMENT=$(jq -n --arg body "$OUTPUT" '{body: $body}')
            curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
              --header "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
              --header "Content-Type: application/json" \
              --data "$COMMENT"
            exit 1
          fi

  check-hash-key:
    name: Check Hash Key
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Hash Key in Files
        run: |
          HASH_KEY=$(cat .hashkey)
          MISSING_FILES=$(find ./app/ -type f \( -name "*.blade.php" -o -name "*.php" \) -not -exec grep -q "$HASH_KEY" {} \; -print)

          if [ ! -z "$MISSING_FILES" ]; then
            OUTPUT="🚨 Hash key không tìm thấy trong các file:\n$MISSING_FILES"
            echo "$OUTPUT"
            COMMENT=$(jq -n --arg body "$OUTPUT" '{body: $body}')
            curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
              --header "Authorization: Bearer ${{ secrets.USER_TOKEN }}" \
              --header "Content-Type: application/json" \
              --data "$COMMENT"
            exit 1
          fi
